// data/wordQuestions.js - 단어 퀴즈 전용 1:1 데이터
const wordQuestions = [
    { kor: "사과 🍎", eng: "apple" },
    { kor: "강아지 🐶", eng: "dog" },
    { kor: "고양이 🐱", eng: "cat" },
    { kor: "바나나 🍌", eng: "banana" },
    { kor: "우유 🥛", eng: "milk" },
    { kor: "책 📖", eng: "book" },
    { kor: "연필 ✏️", eng: "pencil" },
    { kor: "학교 🏫", eng: "school" },
    { kor: "선생님 👩‍🏫", eng: "teacher" },
    { kor: "친구 👫", eng: "friend" },
    { kor: "자동차 🚗", eng: "car" },
    { kor: "버스 🚌", eng: "bus" },
    { kor: "비행기 ✈️", eng: "airplane" },
    { kor: "하늘 ☁️", eng: "sky" },
    { kor: "태양 ☀️", eng: "sun" },
    { kor: "달 🌙", eng: "moon" },
    { kor: "별 ⭐", eng: "star" },
    { kor: "물 💧", eng: "water" },
    { kor: "빵 🍞", eng: "bread" },
    { kor: "피자 🍕", eng: "pizza" },
    { kor: "행복한 😊", eng: "happy" },
    { kor: "슬픈 😢", eng: "sad" },
    { kor: "큰 🐘", eng: "big" },
    { kor: "작은 🐭", eng: "small" },
    { kor: "빨간색 🔴", eng: "red" },
    { kor: "파란색 🔵", eng: "blue" },
    { kor: "노란색 🟡", eng: "yellow" },
    { kor: "초록색 🟢", eng: "green" },
    { kor: "달리기 🏃", eng: "run" },
    { kor: "수영하기 🏊", eng: "swim" },
    // 신체 & 외모
    { kor: "머리 💇", eng: "head" },
    { kor: "얼굴 😊", eng: "face" },
    { kor: "눈 👁️", eng: "eye" },
    { kor: "코 👃", eng: "nose" },
    { kor: "입 👄", eng: "mouth" },
    { kor: "귀 👂", eng: "ear" },
    { kor: "손 ✋", eng: "hand" },
    { kor: "발 🦶", eng: "foot" },
    { kor: "손가락 👆", eng: "finger" },
    { kor: "다리 🦵", eng: "leg" },

    // 가족
    { kor: "아빠 👨", eng: "dad" },
    { kor: "엄마 👩", eng: "mom" },
    { kor: "아기 👶", eng: "baby" },
    { kor: "형/남동생 👦", eng: "brother" },
    { kor: "누나/여동생 👧", eng: "sister" },
    { kor: "할아버지 👴", eng: "grandpa" },
    { kor: "할머니 👵", eng: "grandma" },
    { kor: "가족 👨‍👩‍👧‍👦", eng: "family" },
    { kor: "삼촌 👨‍🦱", eng: "uncle" },
    { kor: "이모 👩‍🦰", eng: "aunt" },

    // 동물
    { kor: "곰 🐻", eng: "bear" },
    { kor: "토끼 🐰", eng: "rabbit" },
    { kor: "원숭이 🐒", eng: "monkey" },
    { kor: "호랑이 🐯", eng: "tiger" },
    { kor: "사자 🦁", eng: "lion" },
    { kor: "코끼리 🐘", eng: "elephant" },
    { kor: "기린 🦒", eng: "giraffe" },
    { kor: "돼지 🐷", eng: "pig" },
    { kor: "소 🐄", eng: "cow" },
    { kor: "양 🐑", eng: "sheep" },
    { kor: "말 🐎", eng: "horse" },
    { kor: "오리 🦆", eng: "duck" },
    { kor: "닭 🐔", eng: "chicken" },
    { kor: "새 🐦", eng: "bird" },
    { kor: "물고기 🐟", eng: "fish" },
    { kor: "상어 🦈", eng: "shark" },
    { kor: "고래 🐋", eng: "whale" },
    { kor: "개구리 🐸", eng: "frog" },
    { kor: "거북이 🐢", eng: "turtle" },
    { kor: "뱀 🐍", eng: "snake" },

    // 음식 & 음료
    { kor: "주스 🧃", eng: "juice" },
    { kor: "고기 🥩", eng: "meat" },
    { kor: "계란 🥚", eng: "egg" },
    { kor: "치즈 🧀", eng: "cheese" },
    { kor: "버터 🧈", eng: "butter" },
    { kor: "수프 🍲", eng: "soup" },
    { kor: "밥 🍚", eng: "rice" },
    { kor: "면 🍜", eng: "noodles" },
    { kor: "케이크 🍰", eng: "cake" },
    { kor: "쿠키 🍪", eng: "cookie" },
    { kor: "아이스크림 🍦", eng: "ice cream" },
    { kor: "초콜릿 🍫", eng: "chocolate" },
    { kor: "사탕 🍬", eng: "candy" },
    { kor: "햄버거 🍔", eng: "hamburger" },
    { kor: "감자튀김 🍟", eng: "fries" },

    // 과일 & 채소
    { kor: "딸기 🍓", eng: "strawberry" },
    { kor: "포도 🍇", eng: "grape" },
    { kor: "오렌지 🍊", eng: "orange" },
    { kor: "수박 🍉", eng: "watermelon" },
    { kor: "복숭아 🍑", eng: "peach" },
    { kor: "레몬 🍋", eng: "lemon" },
    { kor: "파인애플 🍍", eng: "pineapple" },
    { kor: "당근 🥕", eng: "carrot" },
    { kor: "감자 🥔", eng: "potato" },
    { kor: "옥수수 🌽", eng: "corn" },
    { kor: "토마토 🍅", eng: "tomato" },
    { kor: "오이 🥒", eng: "cucumber" },
    { kor: "양파 🧅", eng: "onion" },
    { kor: "버섯 🍄", eng: "mushroom" },
    { kor: "호박 🎃", eng: "pumpkin" },

    // 학용품 & 학교
    { kor: "가방 🎒", eng: "bag" },
    { kor: "필통 ✏️", eng: "pencil case" },
    { kor: "지우개 🧽", eng: "eraser" },
    { kor: "자 📏", eng: "ruler" },
    { kor: "가위 ✂️", eng: "scissors" },
    { kor: "풀 🧴", eng: "glue" },
    { kor: "공책 📓", eng: "notebook" },
    { kor: "크레파스 🖍️", eng: "crayon" },
    { kor: "책상 🖥️", eng: "desk" },
    { kor: "의자 🪑", eng: "chair" },
    { kor: "칠판 ⬛", eng: "blackboard" },
    { kor: "교실 🚪", eng: "classroom" },

    // 옷 & 잡화
    { kor: "옷 👕", eng: "clothes" },
    { kor: "티셔츠 👕", eng: "shirt" },
    { kor: "바지 👖", eng: "pants" },
    { kor: "치마 👗", eng: "skirt" },
    { kor: "원피스 👗", eng: "dress" },
    { kor: "외투 🧥", eng: "coat" },
    { kor: "모자 🧢", eng: "hat" },
    { kor: "신발 👟", eng: "shoes" },
    { kor: "양말 🧦", eng: "socks" },
    { kor: "장갑 🧤", eng: "gloves" },
    { kor: "안경 👓", eng: "glasses" },
    { kor: "우산 ☂️", eng: "umbrella" },
    { kor: "시계 ⌚", eng: "watch" },
    { kor: "반지 💍", eng: "ring" },
    { kor: "지갑 👛", eng: "wallet" },

    // 집 & 가구
    { kor: "집 🏠", eng: "house" },
    { kor: "방 🚪", eng: "room" },
    { kor: "문 🚪", eng: "door" },
    { kor: "창문 🪟", eng: "window" },
    { kor: "침대 🛏️", eng: "bed" },
    { kor: "소파 🛋️", eng: "sofa" },
    { kor: "거울 🪞", eng: "mirror" },
    { kor: "시계 ⏰", eng: "clock" },
    { kor: "수건 🧖", eng: "towel" },
    { kor: "비누 🧼", eng: "soap" },

    // 탈것 & 교통
    { kor: "자전거 🚲", eng: "bike" },
    { kor: "기차 🚂", eng: "train" },
    { kor: "배 ⛵", eng: "ship" },
    { kor: "트럭 🚚", eng: "truck" },
    { kor: "소방차 🚒", eng: "fire truck" },
    { kor: "경찰차 🚓", eng: "police car" },
    { kor: "구급차 🚑", eng: "ambulance" },
    { kor: "택시 🚕", eng: "taxi" },
    { kor: "헬리콥터 🚁", eng: "helicopter" },
    { kor: "로켓 🚀", eng: "rocket" },

    // 장소
    { kor: "공원 🏞️", eng: "park" },
    { kor: "놀이터 🛝", eng: "playground" },
    { kor: "병원 🏥", eng: "hospital" },
    { kor: "마트 🛒", eng: "mart" },
    { kor: "도서관 📚", eng: "library" },
    { kor: "동물원 🦒", eng: "zoo" },
    { kor: "식당 🍽️", eng: "restaurant" },
    { kor: "바다 🏖️", eng: "sea" },
    { kor: "산 ⛰️", eng: "mountain" },
    { kor: "강 🌊", eng: "river" },

    // 자연 & 날씨
    { kor: "구름 ☁️", eng: "cloud" },
    { kor: "비 ☔", eng: "rain" },
    { kor: "눈 ❄️", eng: "snow" },
    { kor: "바람 🌬️", eng: "wind" },
    { kor: "무지개 🌈", eng: "rainbow" },
    { kor: "나무 🌳", eng: "tree" },
    { kor: "꽃 🌸", eng: "flower" },
    { kor: "풀 🌿", eng: "grass" },
    { kor: "돌 🪨", eng: "stone" },
    { kor: "불 🔥", eng: "fire" },

    // 감정 & 상태
    { kor: "화난 😡", eng: "angry" },
    { kor: "배고픈 🤤", eng: "hungry" },
    { kor: "목마른 🥤", eng: "thirsty" },
    { kor: "피곤한 🥱", eng: "tired" },
    { kor: "졸린 🥱", eng: "sleepy" },
    { kor: "신난 😆", eng: "excited" },
    { kor: "무서운 😱", eng: "scared" },
    { kor: "아픈 🤒", eng: "sick" },
    { kor: "귀여운 💕", eng: "cute" },
    { kor: "예쁜 👸", eng: "pretty" },

    // 형용사 & 반댓말
    { kor: "빠른 🐰", eng: "fast" },
    { kor: "느린 🐢", eng: "slow" },
    { kor: "키가 큰 🧍‍♂️", eng: "tall" },
    { kor: "키가 작은 🧍", eng: "short" },
    { kor: "차가운 🧊", eng: "cold" },
    { kor: "뜨거운 🔥", eng: "hot" },
    { kor: "긴 📏", eng: "long" },
    { kor: "좋은 👍", eng: "good" },
    { kor: "나쁜 👎", eng: "bad" },
    { kor: "새로운 🆕", eng: "new" },

    // 색깔
    { kor: "검은색 🖤", eng: "black" },
    { kor: "하얀색 🤍", eng: "white" },
    { kor: "분홍색 🩷", eng: "pink" },
    { kor: "보라색 💜", eng: "purple" },
    { kor: "갈색 🤎", eng: "brown" },
    { kor: "주황색 🧡", eng: "orange" },

    // 동작 & 동사
    { kor: "걷기 🚶", eng: "walk" },
    { kor: "점프하기 ⬆️", eng: "jump" },
    { kor: "먹기 🍽️", eng: "eat" },
    { kor: "마시기 🥛", eng: "drink" },
    { kor: "자기 💤", eng: "sleep" },
    { kor: "놀기 ⚽", eng: "play" },
    { kor: "읽기 📖", eng: "read" },
    { kor: "쓰기 📝", eng: "write" },
    { kor: "듣기 🎧", eng: "listen" },
    { kor: "보기 👁️", eng: "see" },
    { kor: "웃기 😁", eng: "smile" },
    { kor: "울기 😢", eng: "cry" },
    { kor: "노래하기 🎤", eng: "sing" },
    { kor: "춤추기 💃", eng: "dance" },
    { kor: "씻기 🧼", eng: "wash" },

    // 장난감 & 기타
    { kor: "공 ⚽", eng: "ball" },
    { kor: "인형 🎎", eng: "doll" },
    { kor: "로봇 🤖", eng: "robot" },
    { kor: "블록 🧱", eng: "block" },
    { kor: "장난감 🧸", eng: "toy" },
    { kor: "선물 🎁", eng: "gift" },
    { kor: "풍선 🎈", eng: "balloon" },
    { kor: "음악 🎶", eng: "music" },
    { kor: "사진 📷", eng: "photo" },
    { kor: "돈 💰", eng: "money" },

    // 동물 & 곤충
    { kor: "하마 🦛", eng: "hippo" },
    { kor: "코뿔소 🦏", eng: "rhino" },
    { kor: "얼룩말 🦓", eng: "zebra" },
    { kor: "캥거루 🦘", eng: "kangaroo" },
    { kor: "코알라 🐨", eng: "koala" },
    { kor: "판다 🐼", eng: "panda" },
    { kor: "부엉이 🦉", eng: "owl" },
    { kor: "박쥐 🦇", eng: "bat" },
    { kor: "다람쥐 🐿️", eng: "squirrel" },
    { kor: "여우 🦊", eng: "fox" },
    { kor: "늑대 🐺", eng: "wolf" },
    { kor: "악어 🐊", eng: "alligator" },
    { kor: "펭귄 🐧", eng: "penguin" },
    { kor: "낙타 🐪", eng: "camel" },
    { kor: "개미 🐜", eng: "ant" },
    { kor: "나비 🦋", eng: "butterfly" },
    { kor: "벌 🐝", eng: "bee" },
    { kor: "거미 🕷️", eng: "spider" },
    { kor: "달팽이 🐌", eng: "snail" },
    { kor: "무당벌레 🐞", eng: "ladybug" },

    // 해양 생물
    { kor: "문어 🐙", eng: "octopus" },
    { kor: "게 🦀", eng: "crab" },
    { kor: "해파리 🪼", eng: "jellyfish" },
    { kor: "돌고래 🐬", eng: "dolphin" },
    { kor: "불가사리 ⭐", eng: "starfish" },
    { kor: "조개 🦪", eng: "shell" },
    { kor: "새우 🦐", eng: "shrimp" },
    { kor: "오징어 🦑", eng: "squid" },

    // 음식 & 디저트
    { kor: "파이 🥧", eng: "pie" },
    { kor: "도넛 🍩", eng: "donut" },
    { kor: "팬케이크 🥞", eng: "pancake" },
    { kor: "와플 🧇", eng: "waffle" },
    { kor: "팝콘 🍿", eng: "popcorn" },
    { kor: "핫도그 🌭", eng: "hot dog" },
    { kor: "시리얼 🥣", eng: "cereal" },
    { kor: "토스트 🍞", eng: "toast" },
    { kor: "잼 🍯", eng: "jam" },
    { kor: "꿀 🍯", eng: "honey" },
    { kor: "만두 🥟", eng: "dumpling" },
    { kor: "샐러드 🥗", eng: "salad" },

    // 과일 & 채소
    { kor: "체리 🍒", eng: "cherry" },
    { kor: "키위 🥝", eng: "kiwi" },
    { kor: "망고 🥭", eng: "mango" },
    { kor: "멜론 🍈", eng: "melon" },
    { kor: "코코넛 🥥", eng: "coconut" },
    { kor: "블루베리 🫐", eng: "blueberry" },
    { kor: "아보카도 🥑", eng: "avocado" },
    { kor: "가지 🍆", eng: "eggplant" },
    { kor: "마늘 🧄", eng: "garlic" },
    { kor: "브로콜리 🥦", eng: "broccoli" },

    // 직업
    { kor: "의사 👨‍⚕️", eng: "doctor" },
    { kor: "간호사 👩‍⚕️", eng: "nurse" },
    { kor: "경찰관 👮‍♂️", eng: "police officer" },
    { kor: "소방관 🧑‍🚒", eng: "firefighter" },
    { kor: "요리사 🧑‍🍳", eng: "chef" },
    { kor: "농부 🧑‍🌾", eng: "farmer" },
    { kor: "조종사 🧑‍✈️", eng: "pilot" },
    { kor: "우주비행사 🧑‍🚀", eng: "astronaut" },
    { kor: "가수 🧑‍🎤", eng: "singer" },
    { kor: "화가 🎨", eng: "artist" },

    // 운동 & 스포츠
    { kor: "축구 ⚽", eng: "soccer" },
    { kor: "농구 🏀", eng: "basketball" },
    { kor: "야구 ⚾", eng: "baseball" },
    { kor: "테니스 🎾", eng: "tennis" },
    { kor: "수영 🏊", eng: "swimming" },
    { kor: "스케이트 ⛸️", eng: "skate" },
    { kor: "스키 ⛷️", eng: "ski" },
    { kor: "볼링 🎳", eng: "bowling" },
    { kor: "골프 ⛳", eng: "golf" },
    { kor: "요가 🧘", eng: "yoga" },

    // 악기 & 음악
    { kor: "피아노 🎹", eng: "piano" },
    { kor: "기타 🎸", eng: "guitar" },
    { kor: "북 🥁", eng: "drum" },
    { kor: "바이올린 🎻", eng: "violin" },
    { kor: "나팔 🎺", eng: "trumpet" },
    { kor: "마이크 🎤", eng: "microphone" },

    // 전자제품 & 도구
    { kor: "컴퓨터 💻", eng: "computer" },
    { kor: "전화기 📞", eng: "phone" },
    { kor: "카메라 📷", eng: "camera" },
    { kor: "라디오 📻", eng: "radio" },
    { kor: "냉장고 🧊", eng: "refrigerator" },
    { kor: "선풍기 🌬️", eng: "fan" },
    { kor: "열쇠 🔑", eng: "key" },
    { kor: "손전등 🔦", eng: "flashlight" },
    { kor: "망치 🔨", eng: "hammer" },
    { kor: "배터리 🔋", eng: "battery" },

    // 장소 & 건물
    { kor: "학교 🏫", eng: "school" },
    { kor: "은행 🏦", eng: "bank" },
    { kor: "우체국 📮", eng: "post office" },
    { kor: "공항 ✈️", eng: "airport" },
    { kor: "박물관 🏛️", eng: "museum" },
    { kor: "경찰서 🚓", eng: "police station" },
    { kor: "소방서 🚒", eng: "fire station" },
    { kor: "약국 💊", eng: "pharmacy" },
    { kor: "영화관 🎬", eng: "cinema" },
    { kor: "제과점 🥐", eng: "bakery" },

    // 계절 & 시간
    { kor: "봄 🌷", eng: "spring" },
    { kor: "여름 ☀️", eng: "summer" },
    { kor: "가을 🍁", eng: "autumn" },
    { kor: "겨울 ❄️", eng: "winter" },
    { kor: "아침 🌅", eng: "morning" },
    { kor: "오후 🌤️", eng: "afternoon" },
    { kor: "저녁 🌆", eng: "evening" },
    { kor: "밤 🌃", eng: "night" },
    { kor: "오늘 📅", eng: "today" },
    { kor: "내일 📅", eng: "tomorrow" },

    // 요일
    { kor: "월요일 🗓️", eng: "Monday" },
    { kor: "화요일 🗓️", eng: "Tuesday" },
    { kor: "수요일 🗓️", eng: "Wednesday" },
    { kor: "목요일 🗓️", eng: "Thursday" },
    { kor: "금요일 🗓️", eng: "Friday" },
    { kor: "토요일 🗓️", eng: "Saturday" },
    { kor: "일요일 🗓️", eng: "Sunday" },

    // 우주 & 자연
    { kor: "우주 🌌", eng: "space" },
    { kor: "행성 🪐", eng: "planet" },
    { kor: "지구 🌍", eng: "earth" },
    { kor: "해변 🏖️", eng: "beach" },
    { kor: "섬 🏝️", eng: "island" },
    { kor: "동굴 🦇", eng: "cave" },
    { kor: "사막 🐪", eng: "desert" },
    { kor: "숲 🌳", eng: "forest" },
    { kor: "연못 🪷", eng: "pond" },
    { kor: "파도 🌊", eng: "wave" },

    // 집안 물건
    { kor: "이불 🛌", eng: "blanket" },
    { kor: "베개 🛏️", eng: "pillow" },
    { kor: "컵 🥛", eng: "cup" },
    { kor: "접시 🍽️", eng: "plate" },
    { kor: "포크 🍴", eng: "fork" },
    { kor: "숟가락 🥄", eng: "spoon" },
    { kor: "냄비 🍲", eng: "pot" },
    { kor: "빗 梳", eng: "comb" },
    { kor: "휴지 🧻", eng: "tissue" },
    { kor: "쓰레기통 🗑️", eng: "trash can" },

    // 감정 & 느낌
    { kor: "지루한 🥱", eng: "bored" },
    { kor: "놀란 😲", eng: "surprised" },
    { kor: "용감한 🦸", eng: "brave" },
    { kor: "약한 🥺", eng: "weak" },
    { kor: "강한 💪", eng: "strong" },
    { kor: "똑똑한 🧠", eng: "smart" },
    { kor: "조용한 🤫", eng: "quiet" },
    { kor: "시끄러운 🔊", eng: "loud" },
    { kor: "친절한 ☺️", eng: "kind" },
    { kor: "바쁜 🏃‍♂️", eng: "busy" },

    // 위치 & 방향
    { kor: "위 ⬆️", eng: "up" },
    { kor: "아래 ⬇️", eng: "down" },
    { kor: "오른쪽 ➡️", eng: "right" },
    { kor: "왼쪽 ⬅️", eng: "left" },
    { kor: "안 📦", eng: "in" },
    { kor: "밖 🚪", eng: "out" },
    { kor: "앞 🚶", eng: "front" },
    { kor: "뒤 🚶‍♂️", eng: "back" },
    { kor: "옆 👭", eng: "side" },
    { kor: "중간 🎯", eng: "middle" },

    // 행동 & 동사
    { kor: "던지기 ⚾", eng: "throw" },
    { kor: "잡기 🤲", eng: "catch" },
    { kor: "밀기 🫷", eng: "push" },
    { kor: "당기기 🫱", eng: "pull" },
    { kor: "만지기 👆", eng: "touch" },
    { kor: "자르기 ✂️", eng: "cut" },
    { kor: "칠하기 🎨", eng: "paint" },
    { kor: "만들기 🛠️", eng: "make" },
    { kor: "돕기 🤝", eng: "help" },
    { kor: "기다리기 ✋", eng: "wait" },
    { kor: "열기 🚪", eng: "open" },
    { kor: "닫기 🪟", eng: "close" },
    { kor: "찾기 🔍", eng: "find" },
    { kor: "멈추기 🛑", eng: "stop" },
    { kor: "시작하기 🚀", eng: "start" },

    // 상태 & 형용사
    { kor: "무거운 🏋️", eng: "heavy" },
    { kor: "가벼운 🪶", eng: "light" },
    { kor: "어두운 🌙", eng: "dark" },
    { kor: "밝은 ☀️", eng: "bright" },
    { kor: "깨끗한 ✨", eng: "clean" },
    { kor: "더러운 흙", eng: "dirty" },
    { kor: "단단한 🪨", eng: "hard" },
    { kor: "부드러운 ☁️", eng: "soft" },
    { kor: "맛있는 😋", eng: "delicious" },
    { kor: "매운 🌶️", eng: "spicy" },
    { kor: "달콤한 🍬", eng: "sweet" },
    { kor: "시큼한 🍋", eng: "sour" },
    { kor: "짠 🧂", eng: "salty" },
    { kor: "비싼 💰", eng: "expensive" },
    { kor: "싼 🏷️", eng: "cheap" },

    // 기타 매일상 단어
    { kor: "마술 🎩", eng: "magic" },
    { kor: "왕관 👑", eng: "crown" },
    { kor: "비밀번호 🔐", eng: "password" },
    { kor: "영수증 🧾", eng: "receipt" },
    { kor: "약속 🤞", eng: "promise" },
    { kor: "질문 ❓", eng: "question" },
    { kor: "게임 🎮", eng: "game" },
    { kor: "파티 🥳", eng: "party" },
    { kor: "숫자 🔢", eng: "number" },
    { kor: "이름 📛", eng: "name" },

    // 요일 (Days of the Week)
    { kor: "월요일 🗓️", eng: "Monday" },
    { kor: "화요일 🗓️", eng: "Tuesday" },
    { kor: "수요일 🗓️", eng: "Wednesday" },
    { kor: "목요일 🗓️", eng: "Thursday" },
    { kor: "금요일 🗓️", eng: "Friday" },
    { kor: "토요일 🗓️", eng: "Saturday" },
    { kor: "일요일 🗓️", eng: "Sunday" },
    { kor: "평일 💼", eng: "weekday" },
    { kor: "주말 🎈", eng: "weekend" },

    // 월 (Months of the Year)
    { kor: "1월 📅", eng: "January" },
    { kor: "2월 📅", eng: "February" },
    { kor: "3월 📅", eng: "March" },
    { kor: "4월 📅", eng: "April" },
    { kor: "5월 📅", eng: "May" },
    { kor: "6월 📅", eng: "June" },
    { kor: "7월 📅", eng: "July" },
    { kor: "8월 📅", eng: "August" },
    { kor: "9월 📅", eng: "September" },
    { kor: "10월 📅", eng: "October" },
    { kor: "11월 📅", eng: "November" },
    { kor: "12월 📅", eng: "December" },

    // 계절 & 날씨 주기 (Seasons)
    { kor: "봄 🌸", eng: "spring" },
    { kor: "여름 ☀️", eng: "summer" },
    { kor: "가을 🍁", eng: "autumn" },
    { kor: "가을 🍂", eng: "fall" },
    { kor: "겨울 ❄️", eng: "winter" },
    { kor: "우기 🌧️", eng: "rainy season" },
    { kor: "건기 ☀️", eng: "dry season" },

    // 기본 시간 & 날짜 단위 (Time Units)
    { kor: "초 ⏱️", eng: "second" },
    { kor: "분 ⏰", eng: "minute" },
    { kor: "시간 ⌛", eng: "hour" },
    { kor: "하루/날 ☀️", eng: "day" },
    { kor: "주/주일 🗓️", eng: "week" },
    { kor: "월/달 📅", eng: "month" },
    { kor: "해/년 🎆", eng: "year" },
    { kor: "10년 🗓️", eng: "decade" },
    { kor: "100년/세기 🏛️", eng: "century" },
    { kor: "날짜 📅", eng: "date" },
    { kor: "시간 🕒", eng: "time" },

    // 과거/현재/미래 날짜 표현 (Relative Days & Times)
    { kor: "오늘 📍", eng: "today" },
    { kor: "어제 ◀️", eng: "yesterday" },
    { kor: "그저께 ◀️◀️", eng: "the day before yesterday" },
    { kor: "내일 ▶️", eng: "tomorrow" },
    { kor: "모레 ▶️▶️", eng: "the day after tomorrow" },
    { kor: "지금 ⏰", eng: "now" },
    { kor: "요즘 🗓️", eng: "these days" },
    { kor: "이번 주 🗓️", eng: "this week" },
    { kor: "지난주 ◀️", eng: "last week" },
    { kor: "다음 주 ▶️", eng: "next week" },
    { kor: "이번 달 📅", eng: "this month" },
    { kor: "지난달 ◀️", eng: "last month" },
    { kor: "다음 달 ▶️", eng: "next month" },
    { kor: "올해 🎆", eng: "this year" },
    { kor: "작년 ◀️", eng: "last year" },
    { kor: "내년 ▶️", eng: "next year" },

    // 하루의 시간대 (Parts of the Day)
    { kor: "새벽 🌅", eng: "dawn" },
    { kor: "아침 ☀️", eng: "morning" },
    { kor: "정오/낮 12시 🌞", eng: "noon" },
    { kor: "오후 🌤️", eng: "afternoon" },
    { kor: "일몰/해질녘 🌇", eng: "sunset" },
    { kor: "저녁 🌆", eng: "evening" },
    { kor: "밤 🌙", eng: "night" },
    { kor: "자정/밤 12시 🌌", eng: "midnight" },
    { kor: "밤에 🌠", eng: "at night" },
    { kor: "주간/낮 ☀️", eng: "daytime" },

    // 달력 & 시계 관련 단어 (Calendar & Clock)
    { kor: "달력 📅", eng: "calendar" },
    { kor: "시계 ⏰", eng: "clock" },
    { kor: "손목시계 ⌚", eng: "watch" },
    { kor: "알람 🔔", eng: "alarm" },
    { kor: "타이머 ⏱️", eng: "timer" },
    { kor: "일정 📝", eng: "schedule" },
    { kor: "시간표 🏫", eng: "timetable" },
    { kor: "기한/마감 ⏳", eng: "deadline" },
    { kor: "휴일/공휴일 🚩", eng: "holiday" },
    { kor: "방학/휴가 🏖️", eng: "vacation" },
    { kor: "생일 🎂", eng: "birthday" },
    { kor: "기념일 🎁", eng: "anniversary" },

    // 서수 표현 (첫째 날 ~ 열두째 날 / 월 순서)
    { kor: "첫 번째 1️⃣", eng: "first" },
    { kor: "두 번째 2️⃣", eng: "second" },
    { kor: "세 번째 3️⃣", eng: "third" },
    { kor: "네 번째 4️⃣", eng: "fourth" },
    { kor: "다섯 번째 5️⃣", eng: "fifth" },
    { kor: "여섯 번째 6️⃣", eng: "sixth" },
    { kor: "일곱 번째 7️⃣", eng: "seventh" },
    { kor: "여덟 번째 8️⃣", eng: "eighth" },
    { kor: "아홉 번째 9️⃣", eng: "ninth" },
    { kor: "열 번째 🔟", eng: "tenth" },
    { kor: "열한 번째 1️⃣1️⃣", eng: "eleventh" },
    { kor: "열두 번째 1️⃣2️⃣", eng: "twelfth" },
    { kor: "마지막 🔚", eng: "last" },

    // 빈도 및 주기 표현 (Frequency & Recurrence)
    { kor: "매일 ☀️", eng: "daily" },
    { kor: "매주 🗓️", eng: "weekly" },
    { kor: "매월 📅", eng: "monthly" },
    { kor: "매년 🎆", eng: "yearly" },
    { kor: "항상 ♾️", eng: "always" },
    { kor: "자주 🔄", eng: "often" },
    { kor: "가끔 🎲", eng: "sometimes" },
    { kor: "드물게 🧊", eng: "rarely" },
    { kor: "절대 ~않다 🚫", eng: "never" },
    { kor: "일찍 🌅", eng: "early" },
    { kor: "늦게 🌙", eng: "late" },
    { kor: "정각에 ⏰", eng: "on time" },

    // 주요 절기 & 특별한 날 (Special Dates)
    { kor: "새해 🎆", eng: "New Year" },
    { kor: "설날 🙇", eng: "New Year's Day" },
    { kor: "크리스마스 🎄", eng: "Christmas" },
    { kor: "할로윈 🎃", eng: "Halloween" },
    { kor: "추수감사절 🦃", eng: "Thanksgiving" },
    { kor: "부활절 🥚", eng: "Easter" },
    { kor: "어린이날 🎈", eng: "Children's Day" },
    { kor: "어버이날 💐", eng: "Parents' Day" },
    { kor: "스승의 날 👩‍🏫", eng: "Teachers' Day" },
    { kor: "소풍날 🧺", eng: "picnic day" },
    { kor: "운동회 날 🏃", eng: "sports day" },

    // 시제 및 시점 수식어 (Time Modifiers)
    { kor: "이전 ◀️", eng: "before" },
    { kor: "이후 ▶️", eng: "after" },
    { kor: "지나서 ⏰", eng: "past" },
    { kor: "동안 ⏳", eng: "during" },
    { kor: "마침내 🏁", eng: "finally" },
    { kor: "곧 ⚡", eng: "soon" },
    { kor: "최근에 🗞️", eng: "recently" },
    { kor: "나중에 🔜", eng: "later" },
    { kor: "이전에 ⏮️", eng: "ago" },

    // 시간 측정 & 단위 관련 추가 표현
    { kor: "오전 🌅", eng: "AM" },
    { kor: "오후 🌇", eng: "PM" },
    { kor: "반 시간(30분) ⏱️", eng: "half hour" },
    { kor: "15분(1/4시간) ⏱️", eng: "quarter hour" },
    { kor: "정오 ☀️", eng: "midday" },
    { kor: "한밤중 🌌", eng: "nighttime" },
    { kor: "매일 아침 ☀️", eng: "every morning" },
    { kor: "매일 밤 🌙", eng: "every night" },
    { kor: "주말마다 🎈", eng: "every weekend" },

    // 축약형 요일 (Short Form Days)
    { kor: "월 (축약) 🗓️", eng: "Mon" },
    { kor: "화 (축약) 🗓️", eng: "Tue" },
    { kor: "수 (축약) 🗓️", eng: "Wed" },
    { kor: "목 (축약) 🗓️", eng: "Thu" },
    { kor: "금 (축약) 🗓️", eng: "Fri" },
    { kor: "토 (축약) 🗓️", eng: "Sat" },
    { kor: "일 (축약) 🗓️", eng: "Sun" },

    // 축약형 월 (Short Form Months)
    { kor: "1월 (축약) 📅", eng: "Jan" },
    { kor: "2월 (축약) 📅", eng: "Feb" },
    { kor: "3월 (축약) 📅", eng: "Mar" },
    { kor: "4월 (축약) 📅", eng: "Apr" },
    { kor: "5월 (축약) 📅", eng: "May" },
    { kor: "6월 (축약) 📅", eng: "Jun" },
    { kor: "7월 (축약) 📅", eng: "Jul" },
    { kor: "8월 (축약) 📅", eng: "Aug" },
    { kor: "9월 (축약) 📅", eng: "Sep" },
    { kor: "10월 (축약) 📅", eng: "Oct" },
    { kor: "11월 (축약) 📅", eng: "Nov" },
    { kor: "12월 (축약) 📅", eng: "Dec" },

    // 시간 및 날짜 질문 표현
    { kor: "언제 ❓", eng: "when" },
    { kor: "몇 시 ⏰", eng: "what time" },
    { kor: "무슨 요일 🗓️", eng: "what day" },
    { kor: "몇 월 📅", eng: "which month" },

    // 기타 날짜 관련 생활 단어
    { kor: "출석부 📋", eng: "attendance" },
    { kor: "방학숙제 📓", eng: "holiday homework" },
    { kor: "시험일 ✏️", eng: "test day" },
    { kor: "졸업식 🎓", eng: "graduation day" },
    { kor: "입학식 🏫", eng: "entrance day" },
    { kor: "개학일 🎒", eng: "first day of school" },
    { kor: "종학일 🏁", eng: "last day of school" },
    { kor: "현장학습 날 🚌", eng: "field trip day" },
    { kor: "생일 파티 🥳", eng: "birthday party" },
    { kor: "카운트다운 🔢", eng: "countdown" },
    { kor: "D-day 🎯", eng: "D-day" },
    { kor: "달력 표시 📌", eng: "mark the calendar" },
    { kor: "날짜 세기 🔢", eng: "count the days" },
    { kor: "날씨 예보 🌤️", eng: "weather forecast" },
    { kor: "해돋이 🌅", eng: "sunrise" },
    { kor: "노을 🌇", eng: "sunset" },
    { kor: "보름달 🌕", eng: "full moon" },
    { kor: "초승달 🌙", eng: "crescent moon" },
    { kor: "음력 🌙", eng: "lunar calendar" },
    { kor: "양력 ☀️", eng: "solar calendar" },
    { kor: "윤년 📅", eng: "leap year" },
    { kor: "시작일 🏁", eng: "start date" },
    { kor: "종료일 🔚", eng: "end date" },
    { kor: "유효기간 ⏳", eng: "expiration date" },
    { kor: "현재 시간 ⏰", eng: "current time" },
    { kor: "세계 시간 🌍", eng: "world time" },
    { kor: "시차 ✈️", eng: "time difference" },
    { kor: "쉬는 시간 🔔", eng: "recess" },
    { kor: "점심시간 🍱", eng: "lunchtime" },
    { kor: "하교시간 🎒", eng: "after school" },
    { kor: "취침시간 💤", eng: "bedtime" },
    { kor: "기상시간 ⏰", eng: "wake-up time" },
    { kor: "자유시간 🎨", eng: "free time" },
    { kor: "가족의 날 👨‍👩‍👧‍👦", eng: "family day" }
];